/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as PgnIdRouteImport } from './routes/pgn/$id'
import { Route as AuthenticatedWatchRouteImport } from './routes/_authenticated/watch'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedPracticeRouteImport } from './routes/_authenticated/practice'
import { Route as AuthenticatedNewsRouteImport } from './routes/_authenticated/news'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedAnalysisRouteImport } from './routes/_authenticated/analysis'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedSplatRouteImport } from './routes/_authenticated/$'
import { Route as AuthenticatedTrainerIndexRouteImport } from './routes/_authenticated/trainer.index'
import { Route as AuthenticatedStudiesIndexRouteImport } from './routes/_authenticated/studies.index'
import { Route as AuthenticatedGamesIndexRouteImport } from './routes/_authenticated/games.index'
import { Route as PgnStudyIdRouteImport } from './routes/pgn/study.$id'
import { Route as OtelV1TracesRouteImport } from './routes/otel/v1/traces'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedTrainerFamilyRouteImport } from './routes/_authenticated/trainer.$family'
import { Route as AuthenticatedStudiesIdRouteImport } from './routes/_authenticated/studies.$id'
import { Route as AuthenticatedPlayersIdRouteImport } from './routes/_authenticated/players.$id'
import { Route as AuthenticatedPingsIdRouteImport } from './routes/_authenticated/pings.$id'
import { Route as AuthenticatedInvitesIdRouteImport } from './routes/_authenticated/invites.$id'
import { Route as AuthenticatedGamesIdRouteImport } from './routes/_authenticated/games.$id'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const PgnIdRoute = PgnIdRouteImport.update({
  id: '/pgn/$id',
  path: '/pgn/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWatchRoute = AuthenticatedWatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPracticeRoute = AuthenticatedPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNewsRoute = AuthenticatedNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalysisRoute = AuthenticatedAnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSplatRoute = AuthenticatedSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTrainerIndexRoute =
  AuthenticatedTrainerIndexRouteImport.update({
    id: '/trainer/',
    path: '/trainer/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudiesIndexRoute =
  AuthenticatedStudiesIndexRouteImport.update({
    id: '/studies/',
    path: '/studies/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGamesIndexRoute = AuthenticatedGamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const PgnStudyIdRoute = PgnStudyIdRouteImport.update({
  id: '/pgn/study/$id',
  path: '/pgn/study/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OtelV1TracesRoute = OtelV1TracesRouteImport.update({
  id: '/otel/v1/traces',
  path: '/otel/v1/traces',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTrainerFamilyRoute =
  AuthenticatedTrainerFamilyRouteImport.update({
    id: '/trainer/$family',
    path: '/trainer/$family',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudiesIdRoute = AuthenticatedStudiesIdRouteImport.update({
  id: '/studies/$id',
  path: '/studies/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlayersIdRoute = AuthenticatedPlayersIdRouteImport.update({
  id: '/players/$id',
  path: '/players/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPingsIdRoute = AuthenticatedPingsIdRouteImport.update({
  id: '/pings/$id',
  path: '/pings/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInvitesIdRoute = AuthenticatedInvitesIdRouteImport.update({
  id: '/invites/$id',
  path: '/invites/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGamesIdRoute = AuthenticatedGamesIdRouteImport.update({
  id: '/games/$id',
  path: '/games/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/$': typeof AuthenticatedSplatRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/analysis': typeof AuthenticatedAnalysisRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/news': typeof AuthenticatedNewsRoute
  '/practice': typeof AuthenticatedPracticeRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/watch': typeof AuthenticatedWatchRoute
  '/pgn/$id': typeof PgnIdRoute
  '/games/$id': typeof AuthenticatedGamesIdRoute
  '/invites/$id': typeof AuthenticatedInvitesIdRoute
  '/pings/$id': typeof AuthenticatedPingsIdRoute
  '/players/$id': typeof AuthenticatedPlayersIdRoute
  '/studies/$id': typeof AuthenticatedStudiesIdRoute
  '/trainer/$family': typeof AuthenticatedTrainerFamilyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/otel/v1/traces': typeof OtelV1TracesRoute
  '/pgn/study/$id': typeof PgnStudyIdRoute
  '/games/': typeof AuthenticatedGamesIndexRoute
  '/studies/': typeof AuthenticatedStudiesIndexRoute
  '/trainer/': typeof AuthenticatedTrainerIndexRoute
}
export interface FileRoutesByTo {
  '/$': typeof AuthenticatedSplatRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/analysis': typeof AuthenticatedAnalysisRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/news': typeof AuthenticatedNewsRoute
  '/practice': typeof AuthenticatedPracticeRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/watch': typeof AuthenticatedWatchRoute
  '/pgn/$id': typeof PgnIdRoute
  '/': typeof AuthenticatedIndexRoute
  '/games/$id': typeof AuthenticatedGamesIdRoute
  '/invites/$id': typeof AuthenticatedInvitesIdRoute
  '/pings/$id': typeof AuthenticatedPingsIdRoute
  '/players/$id': typeof AuthenticatedPlayersIdRoute
  '/studies/$id': typeof AuthenticatedStudiesIdRoute
  '/trainer/$family': typeof AuthenticatedTrainerFamilyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/otel/v1/traces': typeof OtelV1TracesRoute
  '/pgn/study/$id': typeof PgnStudyIdRoute
  '/games': typeof AuthenticatedGamesIndexRoute
  '/studies': typeof AuthenticatedStudiesIndexRoute
  '/trainer': typeof AuthenticatedTrainerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/$': typeof AuthenticatedSplatRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/analysis': typeof AuthenticatedAnalysisRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/news': typeof AuthenticatedNewsRoute
  '/_authenticated/practice': typeof AuthenticatedPracticeRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/watch': typeof AuthenticatedWatchRoute
  '/pgn/$id': typeof PgnIdRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/games/$id': typeof AuthenticatedGamesIdRoute
  '/_authenticated/invites/$id': typeof AuthenticatedInvitesIdRoute
  '/_authenticated/pings/$id': typeof AuthenticatedPingsIdRoute
  '/_authenticated/players/$id': typeof AuthenticatedPlayersIdRoute
  '/_authenticated/studies/$id': typeof AuthenticatedStudiesIdRoute
  '/_authenticated/trainer/$family': typeof AuthenticatedTrainerFamilyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/otel/v1/traces': typeof OtelV1TracesRoute
  '/pgn/study/$id': typeof PgnStudyIdRoute
  '/_authenticated/games/': typeof AuthenticatedGamesIndexRoute
  '/_authenticated/studies/': typeof AuthenticatedStudiesIndexRoute
  '/_authenticated/trainer/': typeof AuthenticatedTrainerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/admin'
    | '/analysis'
    | '/library'
    | '/news'
    | '/practice'
    | '/settings'
    | '/watch'
    | '/pgn/$id'
    | '/games/$id'
    | '/invites/$id'
    | '/pings/$id'
    | '/players/$id'
    | '/studies/$id'
    | '/trainer/$family'
    | '/api/auth/$'
    | '/otel/v1/traces'
    | '/pgn/study/$id'
    | '/games/'
    | '/studies/'
    | '/trainer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/admin'
    | '/analysis'
    | '/library'
    | '/news'
    | '/practice'
    | '/settings'
    | '/watch'
    | '/pgn/$id'
    | '/'
    | '/games/$id'
    | '/invites/$id'
    | '/pings/$id'
    | '/players/$id'
    | '/studies/$id'
    | '/trainer/$family'
    | '/api/auth/$'
    | '/otel/v1/traces'
    | '/pgn/study/$id'
    | '/games'
    | '/studies'
    | '/trainer'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/$'
    | '/_authenticated/admin'
    | '/_authenticated/analysis'
    | '/_authenticated/library'
    | '/_authenticated/news'
    | '/_authenticated/practice'
    | '/_authenticated/settings'
    | '/_authenticated/watch'
    | '/pgn/$id'
    | '/_authenticated/'
    | '/_authenticated/games/$id'
    | '/_authenticated/invites/$id'
    | '/_authenticated/pings/$id'
    | '/_authenticated/players/$id'
    | '/_authenticated/studies/$id'
    | '/_authenticated/trainer/$family'
    | '/api/auth/$'
    | '/otel/v1/traces'
    | '/pgn/study/$id'
    | '/_authenticated/games/'
    | '/_authenticated/studies/'
    | '/_authenticated/trainer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PgnIdRoute: typeof PgnIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  OtelV1TracesRoute: typeof OtelV1TracesRoute
  PgnStudyIdRoute: typeof PgnStudyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/pgn/$id': {
      id: '/pgn/$id'
      path: '/pgn/$id'
      fullPath: '/pgn/$id'
      preLoaderRoute: typeof PgnIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/watch': {
      id: '/_authenticated/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof AuthenticatedWatchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/practice': {
      id: '/_authenticated/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof AuthenticatedPracticeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/news': {
      id: '/_authenticated/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof AuthenticatedNewsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analysis': {
      id: '/_authenticated/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AuthenticatedAnalysisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$': {
      id: '/_authenticated/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AuthenticatedSplatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trainer/': {
      id: '/_authenticated/trainer/'
      path: '/trainer'
      fullPath: '/trainer/'
      preLoaderRoute: typeof AuthenticatedTrainerIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/studies/': {
      id: '/_authenticated/studies/'
      path: '/studies'
      fullPath: '/studies/'
      preLoaderRoute: typeof AuthenticatedStudiesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/games/': {
      id: '/_authenticated/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof AuthenticatedGamesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/pgn/study/$id': {
      id: '/pgn/study/$id'
      path: '/pgn/study/$id'
      fullPath: '/pgn/study/$id'
      preLoaderRoute: typeof PgnStudyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otel/v1/traces': {
      id: '/otel/v1/traces'
      path: '/otel/v1/traces'
      fullPath: '/otel/v1/traces'
      preLoaderRoute: typeof OtelV1TracesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/trainer/$family': {
      id: '/_authenticated/trainer/$family'
      path: '/trainer/$family'
      fullPath: '/trainer/$family'
      preLoaderRoute: typeof AuthenticatedTrainerFamilyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/studies/$id': {
      id: '/_authenticated/studies/$id'
      path: '/studies/$id'
      fullPath: '/studies/$id'
      preLoaderRoute: typeof AuthenticatedStudiesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/players/$id': {
      id: '/_authenticated/players/$id'
      path: '/players/$id'
      fullPath: '/players/$id'
      preLoaderRoute: typeof AuthenticatedPlayersIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pings/$id': {
      id: '/_authenticated/pings/$id'
      path: '/pings/$id'
      fullPath: '/pings/$id'
      preLoaderRoute: typeof AuthenticatedPingsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invites/$id': {
      id: '/_authenticated/invites/$id'
      path: '/invites/$id'
      fullPath: '/invites/$id'
      preLoaderRoute: typeof AuthenticatedInvitesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/games/$id': {
      id: '/_authenticated/games/$id'
      path: '/games/$id'
      fullPath: '/games/$id'
      preLoaderRoute: typeof AuthenticatedGamesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedSplatRoute: typeof AuthenticatedSplatRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAnalysisRoute: typeof AuthenticatedAnalysisRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedNewsRoute: typeof AuthenticatedNewsRoute
  AuthenticatedPracticeRoute: typeof AuthenticatedPracticeRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedWatchRoute: typeof AuthenticatedWatchRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedGamesIdRoute: typeof AuthenticatedGamesIdRoute
  AuthenticatedInvitesIdRoute: typeof AuthenticatedInvitesIdRoute
  AuthenticatedPingsIdRoute: typeof AuthenticatedPingsIdRoute
  AuthenticatedPlayersIdRoute: typeof AuthenticatedPlayersIdRoute
  AuthenticatedStudiesIdRoute: typeof AuthenticatedStudiesIdRoute
  AuthenticatedTrainerFamilyRoute: typeof AuthenticatedTrainerFamilyRoute
  AuthenticatedGamesIndexRoute: typeof AuthenticatedGamesIndexRoute
  AuthenticatedStudiesIndexRoute: typeof AuthenticatedStudiesIndexRoute
  AuthenticatedTrainerIndexRoute: typeof AuthenticatedTrainerIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedSplatRoute: AuthenticatedSplatRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAnalysisRoute: AuthenticatedAnalysisRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedNewsRoute: AuthenticatedNewsRoute,
  AuthenticatedPracticeRoute: AuthenticatedPracticeRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedWatchRoute: AuthenticatedWatchRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedGamesIdRoute: AuthenticatedGamesIdRoute,
  AuthenticatedInvitesIdRoute: AuthenticatedInvitesIdRoute,
  AuthenticatedPingsIdRoute: AuthenticatedPingsIdRoute,
  AuthenticatedPlayersIdRoute: AuthenticatedPlayersIdRoute,
  AuthenticatedStudiesIdRoute: AuthenticatedStudiesIdRoute,
  AuthenticatedTrainerFamilyRoute: AuthenticatedTrainerFamilyRoute,
  AuthenticatedGamesIndexRoute: AuthenticatedGamesIndexRoute,
  AuthenticatedStudiesIndexRoute: AuthenticatedStudiesIndexRoute,
  AuthenticatedTrainerIndexRoute: AuthenticatedTrainerIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PgnIdRoute: PgnIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  OtelV1TracesRoute: OtelV1TracesRoute,
  PgnStudyIdRoute: PgnStudyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
