// <auto-generated />
using System;
using System.Collections.Generic;
using Chess.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Chess.Backend.Data.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    [Migration("20261003075136_AddOpeningTrainer")]
    partial class AddOpeningTrainer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityAlwaysColumns(modelBuilder);

            modelBuilder.Entity("Chess.Backend.Data.Models.ChessEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("EndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FideTc")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("Ongoing")
                        .HasColumnType("boolean");

                    b.Property<string>("RoundName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RoundUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("chess_events", (string)null);
                });

            modelBuilder.Entity("Chess.Backend.Data.Models.ConsumerPosition", b =>
                {
                    b.Property<string>("GroupId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("AggregateId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("LastSeq")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("GroupId", "AggregateId");

                    b.ToTable("consumer_positions", (string)null);
                });

            modelBuilder.Entity("Chess.Backend.Data.Models.EngineGame", b =>
                {
                    b.Property<Guid>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ended")
                        .HasColumnType("boolean");

                    b.Property<long>("LastSeq")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.HasKey("GameId");

                    b.ToTable("engine_games", (string)null);
                });

            modelBuilder.Entity("Chess.Backend.Data.Models.GameDeadline", b =>
                {
                    b.Property<Guid>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DueAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("LastSeq")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("GameId");

                    b.HasIndex("DueAt");

                    b.ToTable("game_deadlines", (string)null);
                });

            modelBuilder.Entity("Chess.Backend.Data.Models.LibraryGame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Black")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DateText")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("DedupeKey")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)");

                    b.Property<string>("Eco")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Event")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Licence")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.PrimitiveCollection<List<string>>("MovesUci")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("OpeningName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Ply")
                        .HasColumnType("integer");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("Round")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Site")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SourceRef")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("White")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("WorldChampionship")
                        .HasColumnType("boolean");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Black");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Black"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Black"), new[] { "gin_trgm_ops" });

                    b.HasIndex("DedupeKey")
                        .IsUnique();

                    b.HasIndex("Eco");

                    b.HasIndex("Event");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Event"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Event"), new[] { "gin_trgm_ops" });

                    b.HasIndex("White");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("White"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("White"), new[] { "gin_trgm_ops" });

                    b.HasIndex("Year", "Id");

                    b.ToTable("library_games", (string)null);
                });

            modelBuilder.Entity("Chess.Backend.Data.Models.LibraryPosition", b =>
                {
                    b.Property<string>("PositionKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<int>("Ply")
                        .HasColumnType("integer");

                    b.HasKey("PositionKey", "GameId", "Ply");

                    b.HasIndex("GameId");

                    b.ToTable("library_positions", (string)null);
                });

            modelBuilder.Entity("Chess.Backend.Data.Models.NewsItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("PublishedAt", "Id");

                    b.HasIndex("Source", "Url")
                        .IsUnique();

                    b.HasIndex("Source", "PublishedAt", "Id");

                    b.ToTable("news_items", (string)null);
                });

            modelBuilder.Entity("Chess.Backend.Data.Models.NotificationGame", b =>
                {
                    b.Property<Guid>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("BlackId")
                        .HasColumnType("bigint");

                    b.Property<string>("BlackName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("LastSeq")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<long>("WhiteId")
                        .HasColumnType("bigint");

                    b.Property<string>("WhiteName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("GameId");

                    b.ToTable("notification_games", (string)null);
                });

            modelBuilder.Entity("Chess.Backend.Data.Models.Opening", b =>
                {
                    b.Property<string>("PositionKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Eco")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.PrimitiveCollection<List<string>>("MovesUci")
                        .HasColumnType("text[]");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Ply")
                        .HasColumnType("integer");

                    b.HasKey("PositionKey");

                    b.ToTable("openings", (string)null);
                });

            modelBuilder.Entity("Chess.Backend.Data.Models.OutboxOffset", b =>
                {
                    b.Property<string>("StreamId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("LastOrdering")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("StreamId");

                    b.ToTable("outbox_offsets", (string)null);
                });

            modelBuilder.Entity("Chess.Backend.Data.Models.PositionEvaluation", b =>
                {
                    b.Property<string>("PositionKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ThinkMs")
                        .HasColumnType("integer");

                    b.Property<int?>("Depth")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("EvaluatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Lines")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("PositionKey", "ThinkMs");

                    b.ToTable("position_evaluations", (string)null);
                });

            modelBuilder.Entity("Chess.Backend.Data.Models.ProjectionDeadLetter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("FirstFailedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("KafkaKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastError")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("ParkedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Seq")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParkedAt", "Id");

                    b.HasIndex("GroupId", "AggregateId", "Seq");

                    b.ToTable("projection_dead_letters", (string)null);
                });

            modelBuilder.Entity("Chess.Backend.Data.Models.Study", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Black")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Date")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Result")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<bool>("Shared")
                        .HasColumnType("boolean");

                    b.Property<string>("StartFen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Tree")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("White")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "CreatedAt", "Id");

                    b.ToTable("studies", (string)null);
                });

            modelBuilder.Entity("Chess.Backend.Data.Models.TrainerProgress", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("LineKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Color")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<int>("Box")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("DueAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LastClean")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "LineKey", "Color");

                    b.HasIndex("UserId", "Color", "DueAt");

                    b.ToTable("trainer_progress", (string)null);
                });

            modelBuilder.Entity("Chess.Backend.Data.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Preferences")
                        .HasColumnType("jsonb");

                    b.Property<string>("Sub")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Sub")
                        .IsUnique();

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = -1L,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Sub = "engine:1320",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Username = "Stockfish (Casual)",
                            Version = 0L
                        },
                        new
                        {
                            Id = -2L,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Sub = "engine:1600",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Username = "Stockfish (Club)",
                            Version = 0L
                        },
                        new
                        {
                            Id = -3L,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Sub = "engine:2000",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Username = "Stockfish (Expert)",
                            Version = 0L
                        },
                        new
                        {
                            Id = -4L,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Sub = "engine:2400",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Username = "Stockfish (Master)",
                            Version = 0L
                        },
                        new
                        {
                            Id = -5L,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Sub = "engine:max",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Username = "Stockfish (Maximum)",
                            Version = 0L
                        });
                });

            modelBuilder.Entity("Chess.Backend.Data.Models.UserSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("AccessTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("RefreshTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Subject");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("user_sessions", (string)null);
                });

            modelBuilder.Entity("Chess.Backend.Data.ReadModels.RmGame", b =>
                {
                    b.Property<Guid>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("BlackId")
                        .HasColumnType("bigint");

                    b.Property<long>("BlackMs")
                        .HasColumnType("bigint");

                    b.Property<string>("BlackName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastFen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastSan")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<long>("LastSeq")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("LastUci")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Pgn")
                        .HasColumnType("text");

                    b.Property<int>("Ply")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Result")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("TimeControl")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("WhiteId")
                        .HasColumnType("bigint");

                    b.Property<long>("WhiteMs")
                        .HasColumnType("bigint");

                    b.Property<string>("WhiteName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("GameId");

                    b.HasIndex("Status", "UpdatedAt", "GameId");

                    b.ToTable("rm_games", (string)null);
                });

            modelBuilder.Entity("Chess.Backend.Data.ReadModels.RmGamePlayer", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("OpponentId")
                        .HasColumnType("bigint");

                    b.Property<string>("OpponentName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("UserId", "GameId");

                    b.HasIndex("UserId", "CreatedAt", "GameId");

                    b.ToTable("rm_game_players", (string)null);
                });

            modelBuilder.Entity("Chess.Backend.Data.ReadModels.RmMove", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<int>("Ply")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("BlackMs")
                        .HasColumnType("bigint");

                    b.Property<string>("FenAfter")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("San")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Uci")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<long>("WhiteMs")
                        .HasColumnType("bigint");

                    b.HasKey("GameId", "Ply");

                    b.ToTable("rm_moves", (string)null);
                });

            modelBuilder.Entity("Chess.Backend.Data.ReadModels.RmPing", b =>
                {
                    b.Property<string>("PingId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("Count")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("LastAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("LastSeq")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("LastText")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PingId");

                    b.HasIndex("UpdatedAt", "PingId");

                    b.ToTable("rm_pings", (string)null);
                });

            modelBuilder.Entity("Chess.Backend.Data.Models.LibraryPosition", b =>
                {
                    b.HasOne("Chess.Backend.Data.Models.LibraryGame", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
